# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='covert_message',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drop',
            name='signal',
            field=models.CharField(default='none', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drop',
            name='lat',
            field=models.DecimalField(decimal_places=7, max_digits=9),
        ),
        migrations.AlterField(
            model_name='drop',
            name='lng',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
