# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 17:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0002_auto_20170710_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drop',
            name='username',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
