# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0002_auto_20170728_0317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drop',
            old_name='covert_message',
            new_name='message',
        ),
    ]
