# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0003_auto_20170729_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drop',
            name='description',
        ),
    ]
