# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0004_remove_drop_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drop',
            name='signal',
        ),
    ]
