# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0005_remove_drop_signal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drop',
            name='lat',
            field=models.DecimalField(decimal_places=50, max_digits=100),
        ),
        migrations.AlterField(
            model_name='drop',
            name='lng',
            field=models.DecimalField(decimal_places=50, max_digits=100),
        ),
    ]
